spring:
  application:
    name:
      spring-boot-starter-csp

security:
  csp:
    enabled: true
    report-only: false
    generate-nonce: true
    report-uri: "/csp/report"
    directives:
      default-src:
        - "'self'"
      script-src:
        - "'self'"
        - "'strict-dynamic'"
      style-src:
        - "'self'"
      img-src:
        - "'self'"
        - "data:"
        - "https:"
      font-src:
        - "'self'"
        - "https://fonts.gstatic.com"
      connect-src:
        - "'self'"
      frame-ancestors:
        - "'none'"
      base-uri:
        - "'self'"
      form-action:
        - "'self'"
      object-src:
        - "'none'"
      upgrade-insecure-requests: []